fullnameOverride: vector

image:
  tag: 0.23.3-debian

# resources -- Set Vector resource requests and limits.
resources:
  ## Required for HPA to function
  requests:
    cpu: 500m
    memory: 256Mi
  # limits:
  #   cpu: 200m
  #   memory: 256Mi

# customConfig -- Override Vector's default configs, if used **all** options need to be specified
## This section supports using helm templates to populate dynamic values
## Ref: https://vector.dev/docs/reference/configuration/
customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: true
    address: 0.0.0.0:8686
    playground: false
  sources:
    datadog_agent:
      address: 0.0.0.0:8282
      type: datadog_agent
      multiple_outputs: true
      trace_proto: v1v2
    internal_metrics:
      type: internal_metrics
  sinks:
    datadog_logs:
      type: datadog_logs
      inputs:
        - datadog_agent.logs
      default_api_key: <your_datadog_api_key>
      compression: gzip
    datadog_metrics:
      type: datadog_metrics
      inputs:
        - datadog_agent.metrics
        - internal_metrics
      default_api_key: <your_datadog_api_key>
    datadog_traces:
      type: datadog_traces
      inputs:
        - datadog_agent.traces
      default_api_key: <your_datadog_api_key>
    dbg:
      type: console
      encoding:
        codec: json
      inputs:
      - datadog_agent.traces

# livenessProbe -- Override default liveness probe settings, if customConfig is used requires customConfig.api.enabled true
## Requires Vector's API to be enabled
livenessProbe:
  httpGet:
    path: /health
    port: api

# readinessProbe -- Override default readiness probe settings, if customConfig is used requires customConfig.api.enabled true
## Requires Vector's API to be enabled
readinessProbe:
  httpGet:
    path: /health
    port: api