name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name
      working-directory: ./api_gateway

    - name: Cache Trivy DB
      uses: actions/cache@v3
      with:
        path: ~/.cache/trivy  # Cache path for Trivy DB
        key: ${{ runner.os }}-trivy-db
        restore-keys: |
          ${{ runner.os }}-trivy-db

    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Scan image by Trivy
      run: |
        trivy image my-image-name --severity CRITICAL
