name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name
      working-directory: ./api_gateway

    - name: Install Trivy
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.41.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.41.0_Linux-64bit.deb

    - name: Scan image by Trivy
      run: |
        trivy image my-image-name --exit-code 1 --severity HIGH,CRITICAL
