name: K8s Check

on:
  workflow_dispatch:

jobs:
  check_k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          



      - name: Connect to EKS cluster
        run: |
          aws eks update-kubeconfig --region us-east-1 --name production-environment
          kubectl get nodes -o wide
        working-directory: ./infra/

      - name: K8s check
        run: |
          # List all deployments with details
          kubectl get deployments -o wide

          # List all pods with details
          kubectl get pods -o wide


          
